ALTER TABLE messages ADD COLUMN IF NOT EXISTS resource_version integer NOT NULL DEFAULT 1;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS cancelled_at timestamptz;
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_message_tenant_id') THEN
    ALTER TABLE messages ADD CONSTRAINT uq_message_tenant_id UNIQUE (tenant_id, id);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS communication_message_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id varchar(128) NOT NULL,
  message_id uuid NOT NULL,
  event_type varchar(96) NOT NULL,
  previous_status varchar(48),
  new_status varchar(48) NOT NULL,
  actor_id varchar(160) NOT NULL,
  correlation_id varchar(128) NOT NULL,
  safe_detail varchar(240),
  occurred_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT fk_communication_event_message FOREIGN KEY (tenant_id, message_id)
    REFERENCES messages(tenant_id, id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_communication_message_events_tenant_message
  ON communication_message_events(tenant_id, message_id, id);

CREATE TABLE IF NOT EXISTS communication_message_mutations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id varchar(128) NOT NULL,
  message_id uuid NOT NULL,
  mutation_type varchar(48) NOT NULL,
  idempotency_key varchar(200) NOT NULL,
  request_fingerprint varchar(64) NOT NULL,
  result_version integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT fk_communication_mutation_message FOREIGN KEY (tenant_id, message_id)
    REFERENCES messages(tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT uq_communication_message_mutation
    UNIQUE (tenant_id, message_id, mutation_type, idempotency_key)
);

CREATE TABLE IF NOT EXISTS communication_audit_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id varchar(128) NOT NULL,
  aggregate_type varchar(64) NOT NULL,
  aggregate_id uuid NOT NULL,
  action varchar(96) NOT NULL,
  outcome varchar(32) NOT NULL,
  actor_id varchar(160) NOT NULL,
  correlation_id varchar(128) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_communication_audit_tenant_aggregate
  ON communication_audit_events(tenant_id, aggregate_id, created_at);
